/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthRecoveryRouteImport } from './routes/auth/recovery'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppNurseryRouteImport } from './routes/app/nursery'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppCareerRouteImport } from './routes/app/career'
import { Route as AppApplicationsRouteImport } from './routes/app/applications'
import { Route as AppCareerProfileRouteImport } from './routes/app/career.profile'
import { Route as AppCareerCvRouteImport } from './routes/app/career.cv'
import { Route as AppApplicationsApplicationIdRouteImport } from './routes/app/applications.$applicationId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoveryRoute = AuthRecoveryRouteImport.update({
  id: '/auth/recovery',
  path: '/auth/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNurseryRoute = AppNurseryRouteImport.update({
  id: '/nursery',
  path: '/nursery',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerRoute = AppCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerProfileRoute = AppCareerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppCareerRoute,
} as any)
const AppCareerCvRoute = AppCareerCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AppCareerRoute,
} as any)
const AppApplicationsApplicationIdRoute =
  AppApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AppApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/applications': typeof AppApplicationsRouteWithChildren
  '/app/career': typeof AppCareerRouteWithChildren
  '/app/home': typeof AppHomeRoute
  '/app/nursery': typeof AppNurseryRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/app/career/cv': typeof AppCareerCvRoute
  '/app/career/profile': typeof AppCareerProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/applications': typeof AppApplicationsRouteWithChildren
  '/app/career': typeof AppCareerRouteWithChildren
  '/app/home': typeof AppHomeRoute
  '/app/nursery': typeof AppNurseryRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/app/career/cv': typeof AppCareerCvRoute
  '/app/career/profile': typeof AppCareerProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/applications': typeof AppApplicationsRouteWithChildren
  '/app/career': typeof AppCareerRouteWithChildren
  '/app/home': typeof AppHomeRoute
  '/app/nursery': typeof AppNurseryRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/app/career/cv': typeof AppCareerCvRoute
  '/app/career/profile': typeof AppCareerProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/applications'
    | '/app/career'
    | '/app/home'
    | '/app/nursery'
    | '/app/settings'
    | '/auth/recovery'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/applications/$applicationId'
    | '/app/career/cv'
    | '/app/career/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/applications'
    | '/app/career'
    | '/app/home'
    | '/app/nursery'
    | '/app/settings'
    | '/auth/recovery'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/applications/$applicationId'
    | '/app/career/cv'
    | '/app/career/profile'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/applications'
    | '/app/career'
    | '/app/home'
    | '/app/nursery'
    | '/app/settings'
    | '/auth/recovery'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/applications/$applicationId'
    | '/app/career/cv'
    | '/app/career/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/auth/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nursery': {
      id: '/app/nursery'
      path: '/nursery'
      fullPath: '/app/nursery'
      preLoaderRoute: typeof AppNurseryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/career': {
      id: '/app/career'
      path: '/career'
      fullPath: '/app/career'
      preLoaderRoute: typeof AppCareerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/career/profile': {
      id: '/app/career/profile'
      path: '/profile'
      fullPath: '/app/career/profile'
      preLoaderRoute: typeof AppCareerProfileRouteImport
      parentRoute: typeof AppCareerRoute
    }
    '/app/career/cv': {
      id: '/app/career/cv'
      path: '/cv'
      fullPath: '/app/career/cv'
      preLoaderRoute: typeof AppCareerCvRouteImport
      parentRoute: typeof AppCareerRoute
    }
    '/app/applications/$applicationId': {
      id: '/app/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/app/applications/$applicationId'
      preLoaderRoute: typeof AppApplicationsApplicationIdRouteImport
      parentRoute: typeof AppApplicationsRoute
    }
  }
}

interface AppApplicationsRouteChildren {
  AppApplicationsApplicationIdRoute: typeof AppApplicationsApplicationIdRoute
}

const AppApplicationsRouteChildren: AppApplicationsRouteChildren = {
  AppApplicationsApplicationIdRoute: AppApplicationsApplicationIdRoute,
}

const AppApplicationsRouteWithChildren = AppApplicationsRoute._addFileChildren(
  AppApplicationsRouteChildren,
)

interface AppCareerRouteChildren {
  AppCareerCvRoute: typeof AppCareerCvRoute
  AppCareerProfileRoute: typeof AppCareerProfileRoute
}

const AppCareerRouteChildren: AppCareerRouteChildren = {
  AppCareerCvRoute: AppCareerCvRoute,
  AppCareerProfileRoute: AppCareerProfileRoute,
}

const AppCareerRouteWithChildren = AppCareerRoute._addFileChildren(
  AppCareerRouteChildren,
)

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRouteWithChildren
  AppCareerRoute: typeof AppCareerRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppNurseryRoute: typeof AppNurseryRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRouteWithChildren,
  AppCareerRoute: AppCareerRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppNurseryRoute: AppNurseryRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
